/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.53
 * Generated at: 2014-04-25 06:27:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class echo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/tlds/site-utils.tld", Long.valueOf(1398239004662L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsite_002dutils_005flastModified_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsite_002dutils_005ftextInput_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fsite_002dutils_005flastModified_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsite_002dutils_005ftextInput_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fsite_002dutils_005flastModified_005fnobody.release();
    _005fjspx_005ftagPool_005fsite_002dutils_005ftextInput_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h1>\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${aJspValue}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"</h1>\r\n");
      out.write("\t<h2>\r\n");
      out.write("\t\t");
      if (_jspx_meth_site_002dutils_005flastModified_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t</h2>\r\n");
      out.write("\t");
      if (_jspx_meth_site_002dutils_005ftextInput_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t<div class=\"tableForm\">\r\n");
      out.write("\t\t<form action=\"product/tableform.cmd\" method=\"post\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"formType\" value=\"tableForm\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"className\" value=\"ming.bean.FormBean\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>值1</td>\r\n");
      out.write("\t\t\t\t\t\t<td>值2</td>\r\n");
      out.write("\t\t\t\t\t\t<td>值3</td>\r\n");
      out.write("\t\t\t\t\t\t<td>值4</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><input name=\"value1\" value=\"值1\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input name=\"value2\" value=\"值2\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input name=\"value3\" value=\"值3\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input name=\"value4\" value=\"值4\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><input name=\"value1\" value=\"A值1\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input name=\"value2\" value=\"A值2\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input name=\"value3\" value=\"A值3\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input name=\"value4\" value=\"A值4\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><input name=\"value1\" value=\"\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input name=\"value2\" value=\"\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input name=\"value3\" value=\"\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input name=\"value4\" value=\"B值4\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"comment\" value=\"支持的数据类型应该有字符串，数字，可格式化的小数，金额。输入形式有文本框，下拉选择框，日期，（复选框和单选框稍后加）\">\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"提交\">\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_site_002dutils_005flastModified_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  site-utils:lastModified
    ming.tag.LastModifiedTag _jspx_th_site_002dutils_005flastModified_005f0 = (ming.tag.LastModifiedTag) _005fjspx_005ftagPool_005fsite_002dutils_005flastModified_005fnobody.get(ming.tag.LastModifiedTag.class);
    _jspx_th_site_002dutils_005flastModified_005f0.setPageContext(_jspx_page_context);
    _jspx_th_site_002dutils_005flastModified_005f0.setParent(null);
    int _jspx_eval_site_002dutils_005flastModified_005f0 = _jspx_th_site_002dutils_005flastModified_005f0.doStartTag();
    if (_jspx_th_site_002dutils_005flastModified_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fsite_002dutils_005flastModified_005fnobody.reuse(_jspx_th_site_002dutils_005flastModified_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fsite_002dutils_005flastModified_005fnobody.reuse(_jspx_th_site_002dutils_005flastModified_005f0);
    return false;
  }

  private boolean _jspx_meth_site_002dutils_005ftextInput_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  site-utils:textInput
    ming.tag.TextInputTag _jspx_th_site_002dutils_005ftextInput_005f0 = (ming.tag.TextInputTag) _005fjspx_005ftagPool_005fsite_002dutils_005ftextInput_005fnobody.get(ming.tag.TextInputTag.class);
    _jspx_th_site_002dutils_005ftextInput_005f0.setPageContext(_jspx_page_context);
    _jspx_th_site_002dutils_005ftextInput_005f0.setParent(null);
    int _jspx_eval_site_002dutils_005ftextInput_005f0 = _jspx_th_site_002dutils_005ftextInput_005f0.doStartTag();
    if (_jspx_th_site_002dutils_005ftextInput_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fsite_002dutils_005ftextInput_005fnobody.reuse(_jspx_th_site_002dutils_005ftextInput_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fsite_002dutils_005ftextInput_005fnobody.reuse(_jspx_th_site_002dutils_005ftextInput_005f0);
    return false;
  }
}
